const JSON = [
    
    {
        "Id": 1,
        "Nome": "PERFUME DIOR SAUVAGE MASCULINO EAU DE TOILETTE",
        "Preconormal": 489.99,
        "Marca": "Dior",
        "Tipo": "Amadeirado",
        "Genero": "Masculino",
        "Especial": false,
        "MediaAvaliacao": 5,
        "Descricao": "François Demachy, perfumista-Criador de Dior, inspirou-se no deserto, na hora mágica do crepúsculo. Misturado com a frieza da noite, o ar ardente do deserto exala fragrâncias profundas. Na hora em que os lobos saem e o céu é incendiado, uma nova magia se desenrola. A bergamota da Calábria, tão suculenta e espirituosa como sempre, convida novas notas picantes a aumentar a plenitude e a sensualidade, já que o rastro ambarado do Ambroxan® está envolto nos acentos esfumados do absoluto da baunilha de Papua Nova Guiné, para maior virilidade.",
        "Oferta": false,
        "PrecoOferta": 0,
        "Estoque": 100,
    },
    {
        "Id": 2,
        "Nome": "PERFUME K DOLCE & GABANNA MASCULINO EAU DE TOILETTE",
        "Preconormal": 589.99,
        "Marca":"Dolce & Gabanna",
        "Tipo": "Amadeirado",
        "Genero": "Masculino",
        "Especial": false,
        "MediaAvaliacao": 5,
        "Descricao": "François Demachy, perfumista-Criador de Dior, inspirou-se no deserto, na hora mágica do crepúsculo. Misturado com a frieza da noite, o ar ardente do deserto exala fragrâncias profundas. Na hora em que os lobos saem e o céu é incendiado, uma nova magia se desenrola. A bergamota da Calábria, tão suculenta e espirituosa como sempre, convida novas notas picantes a aumentar a plenitude e a sensualidade, já que o rastro ambarado do Ambroxan® está envolto nos acentos esfumados do absoluto da baunilha de Papua Nova Guiné, para maior virilidade.",
        "Oferta": false,
        "PrecoOferta": 0,
        "Estoque": 100,
        
    },
    {
        "Id": 3,
        "Nome": "PERFUME VERSACE POUR HOMME MASCULINO EUA DE TOILETTE",
        "Preconormal": 599.99,
        "Marca": "Versace",
        "Tipo": "Aromatico",
        "Genero": "Masculino",
        "Especial": false,
        "MediaAvaliacao": 5,
        "Descricao": "François Demachy, perfumista-Criador de Dior, inspirou-se no deserto, na hora mágica do crepúsculo. Misturado com a frieza da noite, o ar ardente do deserto exala fragrâncias profundas. Na hora em que os lobos saem e o céu é incendiado, uma nova magia se desenrola. A bergamota da Calábria, tão suculenta e espirituosa como sempre, convida novas notas picantes a aumentar a plenitude e a sensualidade, já que o rastro ambarado do Ambroxan® está envolto nos acentos esfumados do absoluto da baunilha de Papua Nova Guiné, para maior virilidade.",
        "Oferta": false,
        "PrecoOferta": 0,
        "Estoque": 100,
    },
    {
        "Id": 4,
        "Nome": "PERFUME PACO RABANE PHANTOM MASCULINO EAU DE TOILETTE",
        "Preconormal": 469.99,
        "Marca": "Paco Rabanne",
        "Tipo": "Aromatico",
        "Genero": "Masculino",
        "Especial": false,
        "MediaAvaliacao": 5,
        "Descricao": "François Demachy, perfumista-Criador de Dior, inspirou-se no deserto, na hora mágica do crepúsculo. Misturado com a frieza da noite, o ar ardente do deserto exala fragrâncias profundas. Na hora em que os lobos saem e o céu é incendiado, uma nova magia se desenrola. A bergamota da Calábria, tão suculenta e espirituosa como sempre, convida novas notas picantes a aumentar a plenitude e a sensualidade, já que o rastro ambarado do Ambroxan® está envolto nos acentos esfumados do absoluto da baunilha de Papua Nova Guiné, para maior virilidade.",
        "Oferta": false,
        "PrecoOferta": 0,
        "Estoque": 100,
        
    },
    {
        "Id": 5,
        "Nome": "PERFUME HYPNOTIC POISON DIOR FEMININO EAU DE TOILETTE",
        "Preconormal": 399.99,
        "Marca": "Dior",
        "Tipo": "Frutal",
        "Genero": "Feminino",
        "Especial": false,
        "MediaAvaliacao": 5,
        "Descricao": "François Demachy, perfumista-Criador de Dior, inspirou-se no deserto, na hora mágica do crepúsculo. Misturado com a frieza da noite, o ar ardente do deserto exala fragrâncias profundas. Na hora em que os lobos saem e o céu é incendiado, uma nova magia se desenrola. A bergamota da Calábria, tão suculenta e espirituosa como sempre, convida novas notas picantes a aumentar a plenitude e a sensualidade, já que o rastro ambarado do Ambroxan® está envolto nos acentos esfumados do absoluto da baunilha de Papua Nova Guiné, para maior virilidade.",
        "Oferta": false,
        "PrecoOferta": 0,
        "Estoque": 100,
    },
    {
        "Id": 6,
        "Nome": "PERFUME Q BY DOLCE & GABBANA FEMININO EAU DE PARFUM",
        "Preconormal": 799.99,
        "Marca": "Dolce & Gabanna",
        "Tipo": "Aromatico",
        "Genero": "Feminino",
        "Especial": false,
        "MediaAvaliacao": 5,
        "Descricao": "François Demachy, perfumista-Criador de Dior, inspirou-se no deserto, na hora mágica do crepúsculo. Misturado com a frieza da noite, o ar ardente do deserto exala fragrâncias profundas. Na hora em que os lobos saem e o céu é incendiado, uma nova magia se desenrola. A bergamota da Calábria, tão suculenta e espirituosa como sempre, convida novas notas picantes a aumentar a plenitude e a sensualidade, já que o rastro ambarado do Ambroxan® está envolto nos acentos esfumados do absoluto da baunilha de Papua Nova Guiné, para maior virilidade.",
        "Oferta": false,
        "PrecoOferta": 0,
        "Estoque": 100,
    },
    {
        "Id": 7,
        "Nome": "PERFUME VERSACE DYLAN PURPLE FEMININO EUA DE PARFUM",
        "Preconormal": 749.99,
        "Marca": "Versace",
        "Tipo": "Floral",
        "Genero": "Feminino",
        "Especial": false,
        "MediaAvaliacao": 5,
        "Descricao": "François Demachy, perfumista-Criador de Dior, inspirou-se no deserto, na hora mágica do crepúsculo. Misturado com a frieza da noite, o ar ardente do deserto exala fragrâncias profundas. Na hora em que os lobos saem e o céu é incendiado, uma nova magia se desenrola. A bergamota da Calábria, tão suculenta e espirituosa como sempre, convida novas notas picantes a aumentar a plenitude e a sensualidade, já que o rastro ambarado do Ambroxan® está envolto nos acentos esfumados do absoluto da baunilha de Papua Nova Guiné, para maior virilidade.",
        "Oferta": false,
        "PrecoOferta": 0,
        "Estoque": 100,
    },
    {
        "Id": 8,
        "Nome": "PERFUME FAME BLOOMING PINK PACO RABANNE FEMININO EAU DE PARFUM",
        "Preconormal": 749.99,
        "Marca": "Paco Rabanne",
        "Tipo": "Floral",
        "Genero": "Feminino",
        "Especial": false,
        "MediaAvaliacao": 5,
        "Descricao": "François Demachy, perfumista-Criador de Dior, inspirou-se no deserto, na hora mágica do crepúsculo. Misturado com a frieza da noite, o ar ardente do deserto exala fragrâncias profundas. Na hora em que os lobos saem e o céu é incendiado, uma nova magia se desenrola. A bergamota da Calábria, tão suculenta e espirituosa como sempre, convida novas notas picantes a aumentar a plenitude e a sensualidade, já que o rastro ambarado do Ambroxan® está envolto nos acentos esfumados do absoluto da baunilha de Papua Nova Guiné, para maior virilidade.",
        "Oferta": false,
        "PrecoOferta": 0,
        "Estoque": 100,
    },

]

export default JSON